spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/warehouse_management
    username: postgres
    password: manzi123
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
